apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-dev
  labels:
    environment: dev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/postgres-dev